import {StyleSheet} from 'react-native';
export const style = StyleSheet.create({
  Container: {
    backgroundColor: '#e8edef',
    flex: 1,
  },
  Banner: {
    height: 180,
    width: 325,
    alignSelf: 'center',
    marginTop: 10,
    borderRadius: 10,
  },
  catWrapper: {},
  titleAndViewAll: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    padding: 10,
  },
  catTitle: {
    fontSize: 16,
    marginLeft: 10,
    fontWeight: 'bold',
    color: 'black',
  },
  viewAllTitle: {
    marginRight: 10,
    color: 'red',
  },
  item: {
    height: 130,
    width: 150,
    marginTop: 20,
    marginRight: 5,
    marginLeft: 15,
    backgroundColor: '#fff',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    borderColor: 'red',
    borderWidth: 1,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  catImg: {
    marginTop: 10,
    height: 80,
    width: 80,
  },
  catName: {
    fontSize: 15,
    color: 'black',
    marginTop: 5,
    backgroundColor: 'white',
    alignItems: 'center',
  },
  PopularText: {
    fontSize: 16,
    marginLeft: 10,
    fontWeight: 'bold',
    color: 'black',
    marginTop: 20,
    marginLeft: 20,
  },
  PopularItemWrapper: {
    marginTop: 25,

    backgroundColor: '#fff',
    width: 140,
    height: 310,
    marginLeft: 15,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'green',
    alignItems: 'center',
    marginBottom: 15,
  },
  PopularImg: {
    height: 140,
    width: 140,
    alignSelf: 'center',
  },
  saleText: {
    borderRadius: 10,

    backgroundColor: 'green',
    marginTop: 10,
    color: 'white',
    width: 80,
    height: 20,
    justifyContent: 'center',
    textAlign: 'center',
    alignSelf: 'center',
  },

  pItemPrice: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#111',
    marginLeft: 10,
  },
  pItemName: {
    marginTop: 10,
    fontSize: 16,
    marginLeft: 10,
    height: 60,
  },

  cartBtn: {
    marginTop: 15,
    backgroundColor: 'green',
    width: 120,
    height: 22,
    textAlign: 'center',
    color: '#fff',
    borderRadius: 15,
    justifyContent: 'center',
  },
});
